import { sql, type AnyColumn, type SQL } from "drizzle-orm";
import { timestamp, uuid } from "drizzle-orm/pg-core";

/** Primary key generated by Postgres; Better Auth is configured with `generateId: "uuid"`. */
export const id = () =>
  uuid("id")
    .primaryKey()
    .default(sql`gen_random_uuid()`);

/** Every timestamp is `timestamptz`: instants, never wall-clock times. */
export const timestamptz = (name: string) => timestamp(name, { withTimezone: true });

export const createdAt = () => timestamptz("created_at").notNull().defaultNow();

export const updatedAt = () =>
  timestamptz("updated_at")
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date());

/**
 * `column in ('a', 'b')` for check constraints. Sets of values are `text` +
 * check rather than Postgres enums: `ALTER TYPE ... ADD VALUE` cannot be used
 * in the transaction that adds it, and migrations run in one transaction.
 * Values are compile-time constants, never user input.
 */
export function oneOf(column: AnyColumn, values: readonly string[]): SQL {
  const list = values.map((value) => `'${value.replaceAll("'", "''")}'`).join(", ");
  return sql`${column} in (${sql.raw(list)})`;
}
